# Generated by Django 6.0.3 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='en', max_length=2, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分类名称'),
        ),
    ]
