# Generated by Django 6.0.3 on 2026-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AI Blog', max_length=100, verbose_name='网站名称')),
                ('site_description', models.TextField(blank=True, max_length=300, verbose_name='网站描述')),
                ('hero_title', models.CharField(default='探索AI与技术的无限可能', max_length=100, verbose_name='Hero标题')),
                ('hero_subtitle', models.CharField(default='用代码构建未来，用思想连接世界', max_length=200, verbose_name='Hero副标题')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Hero背景图')),
                ('author_name', models.CharField(default='Your Name', max_length=50, verbose_name='作者姓名')),
                ('author_title', models.CharField(default='Full Stack Developer', max_length=100, verbose_name='作者头衔')),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='作者头像')),
                ('author_bio', models.TextField(blank=True, max_length=500, verbose_name='作者简介')),
                ('service_1_title', models.CharField(default='开发服务', max_length=50, verbose_name='服务1标题')),
                ('service_1_desc', models.CharField(default='提供专业的Web应用开发服务', max_length=200, verbose_name='服务1描述')),
                ('service_1_icon', models.CharField(default='code', help_text='Lucide图标名称', max_length=50, verbose_name='服务1图标')),
                ('service_2_title', models.CharField(default='技术咨询', max_length=50, verbose_name='服务2标题')),
                ('service_2_desc', models.CharField(default='提供技术架构和方案咨询服务', max_length=200, verbose_name='服务2描述')),
                ('service_2_icon', models.CharField(default='lightbulb', max_length=50, verbose_name='服务2图标')),
                ('service_3_title', models.CharField(default='内容创作', max_length=50, verbose_name='服务3标题')),
                ('service_3_desc', models.CharField(default='撰写高质量技术博客和教程', max_length=200, verbose_name='服务3描述')),
                ('service_3_icon', models.CharField(default='pen-tool', max_length=50, verbose_name='服务3图标')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('contact_github', models.URLField(blank=True, verbose_name='GitHub')),
                ('contact_linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('contact_twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('footer_text', models.CharField(default='© 2026 AI Blog. All rights reserved.', max_length=200, verbose_name='页脚文字')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
