# Generated by Django 6.0.3 on 2026-03-16 08:58

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(help_text='支持 Markdown 语法，可使用 @[文章标题] 引用内部文章', verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_subtitle',
            field=models.CharField(default='探索技术世界的点滴思考', help_text='支持 @[文章标题] 引用内部文章链接', max_length=200, verbose_name='博客副标题'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_title',
            field=models.CharField(default='博客文章', max_length=100, verbose_name='博客标题'),
        ),
    ]
