# Generated by Django 6.0.3 on 2026-03-16 09:39

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_sitesettings_blog_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_background',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_1_desc',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_1_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_1_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_2_desc',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_2_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_2_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_3_desc',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_3_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='service_3_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='支持 Markdown 语法和图片上传，可使用 @[文章标题] 引用内部文章', verbose_name='我的服务'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='author_bio',
            field=markdownx.models.MarkdownxField(blank=True, help_text='支持 Markdown 语法，可使用 @[文章标题] 引用内部文章', verbose_name='作者简介'),
        ),
    ]
