# Generated by Django 6.0.3 on 2026-03-16 10:27

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_hero_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='主标题')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('welcome_text', markdownx.models.MarkdownxField(help_text='支持 Markdown 语法', verbose_name='欢迎词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Hero页面',
                'verbose_name_plural': 'Hero页面',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(help_text='支持 Markdown 语法', verbose_name='CTA内容')),
                ('button_text', models.CharField(default='了解更多', max_length=100, verbose_name='按钮文字')),
                ('link_type', models.CharField(choices=[('internal', '内部链接'), ('external', '外部链接')], default='internal', max_length=10, verbose_name='链接类型')),
                ('internal_link', models.CharField(blank=True, help_text='如: /about/, /blog/', max_length=200, verbose_name='内部链接')),
                ('external_url', models.URLField(blank=True, verbose_name='外部URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hero_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='core.heropage', verbose_name='所属页面')),
            ],
            options={
                'verbose_name': 'CTA',
                'verbose_name_plural': 'CTA',
            },
        ),
        migrations.CreateModel(
            name='HeroContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='块标题')),
                ('content', markdownx.models.MarkdownxField(help_text='支持 Markdown 语法', verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/blocks/', verbose_name='图片')),
                ('image_position', models.CharField(choices=[('left', '左侧'), ('right', '右侧'), ('center', '居中'), ('none', '不显示图片')], default='right', max_length=10, verbose_name='图片位置')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hero_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.heropage', verbose_name='所属页面')),
            ],
            options={
                'verbose_name': '内容块',
                'verbose_name_plural': '内容块',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
