# Generated by Django 6.0.3 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_hero_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='en', max_length=2, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='heropage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='en', max_length=2, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='en', max_length=2, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_subtitle',
            field=models.CharField(default='Exploring thoughts on technology', help_text='支持 @[文章标题] 引用内部文章链接', max_length=200, verbose_name='博客副标题'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_title',
            field=models.CharField(default='Blog', max_length=100, verbose_name='博客标题'),
        ),
    ]
