# Generated by Django 5.2.12 on 2026-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_language_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文')], default='en', max_length=10, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='heropage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文')], default='en', max_length=10, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文')], default='en', max_length=10, verbose_name='语言'),
        ),
    ]
