# Generated by Django 6.0.3 on 2026-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_announcement_language_alter_heropage_language_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.UniqueConstraint(fields=('language',), name='unique_site_settings_per_language'),
        ),
    ]
