# Generated by Django 6.0.3 on 2026-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_unique_constraint_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropage',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/backgrounds/', verbose_name='背景图'),
        ),
    ]
