# Generated by Django 6.0.3 on 2026-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocta',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/cta/', verbose_name='背景图'),
        ),
    ]
