# Generated by Django 6.0.3 on 2026-03-14 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL别名')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='封面图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10, verbose_name='发布状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categories.category', verbose_name='所属分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_articl_status_47bfec_idx'), models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx')],
            },
        ),
    ]
