# Generated by Django 6.0.3 on 2026-03-16 08:19

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='支持 Markdown 语法，可拖拽上传图片', verbose_name='文章内容'),
        ),
    ]
