# Generated by Django 6.0.3 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_content'),
        ('categories', '0002_add_language_field'),
        ('tags', '0002_add_language_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='blog_articl_status_47bfec_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='en', max_length=2, verbose_name='语言'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['language', 'status', '-published_at'], name='blog_articl_languag_730904_idx'),
        ),
    ]
