# Generated by Django 5.2.12 on 2026-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_language_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文')], default='en', max_length=10, verbose_name='语言'),
        ),
    ]
